### ISSUE TITLE
Add another "type" of survey object - Other

### ISSUE THREAD

**Issue by NicholasDanks** [SurveyMoonBear/SurveyMoonbear_APP#25]
For when we want to specify a multiple choice with an "other" and a short description: Eg.:
- [ ] Male
- [ ] Female
- [ ] Other, description:  __________________________________

**Comment by soumyaray** [comment]
Approved!  Let’s try to get this added in coming months.

**Comment by soumyaray** [comment]
Apparently fixed already!  It's a new item type called 'multiple choice with other' for both radio buttons and checkboxes.
