### ISSUE TITLE
FEATURE REQUEST: Logic Flow

### ISSUE THREAD

**Issue by soumyaray** [SurveyMoonBear/SurveyMoonbear_APP#36]
Allow users to define logic to move to other pages. 
- should have to click 'next page' button to execute logic to decide next page.
- on next page, we should know what is the appropriate 'previous page' to go to.

How logic works:
make it a new item type called "logical flow"
in options column: "group=1, next_page=3; group=2, next_page=4"
- could look at an item's response value to decide (e.g., a multiple choice value)
- could look at other survey URL's parameter values

**Comment by chinyakao** [comment]
Finish this feature on these PRs #66 #70 #71 #75
It is merged into develop branch
