### ISSUE TITLE
FEATURE REQUEST: Allow items to use response from previous items

### ISSUE THREAD

**Issue by soumyaray** [SurveyMoonBear/SurveyMoonbear_APP#37]
Let users use previous answers to formulate new item's wording.

e.g.
page 1: multiple choice item called phone_type (iphone/android/blackberry/feature phone)
page 2: satisfaction question with description: "How do you like your {{phone_type}}?"

**Comment by chinyakao** [comment]
Finish this feature on these two PR #70 #75 
It is merged into develop branch
